#pragma config(Sensor, in1,    xAccel,         sensorAccelerometer)
#pragma config(Sensor, in2,    yAccel,         sensorAccelerometer)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void waitForRelease()
{
	while(nLCDButtons != 0){}
	wait1Msec(5);
}

/////
// LCD Void
/////
void LCD()
{
	/* User Control Menu */
	while (page == 0) 
	{
		clearLCDLine(0);
		clearLCDLine(1);

		displayLCDCenteredString(0, "User Control");
		displayLCDCenteredString(1, "<   Select   >");

		if (nLCDButtons == left)
		{
			waitForRelease();
			page = 3;
		}
		else if (nLCDButtons == right)
		{
			waitForRelease();
			page = 1;
		}
		else if (nLCDButtons == center)
		{
			waitForRelease();
			Program = 1;
		}
	}

	/* Autonomous Menu */
	while (page == 1)
	{
		clearLCDLine(0);
		clearLCDLine(1);

		displayLCDCenteredString(0, "Autonomous");
		displayLCDCenteredString(1, "<   Select   >");

		if (nLCDButtons == left)
		{
			waitForRelease();
			page = 0;
		}
		else if (nLCDButtons == right)
		{
			waitForRelease();
			page = 2;
		}
		else if (nLCDButtons == center)
		{
			waitForRelease();
			Program = 2;
		}
	}
	
	/* Silly Auton */
	while (page == 2)
	{
		clearLCDLine(0);
		clearLCDLine(1);

		displayLCDCenteredString(0, "Silly Auton");
		displayLCDCenteredString(1, "<   Select   >");
		
		if (nLCDButtons == left)
		{
			waitForRelease();
			page = 1;
		}
		
		else if (nLCDButtons == right)
		{
			waitForRelease();
			page = 3;
		}
		
		else if (nLCDButtons == center)
		{
			waitForRelease();
			Program = 3;
		}
	}
	
	/* Testing Menu */
	while (page == 3)
	{
		clearLCDLine(0);
		clearLCDLine(1);

		displayLCDCenteredString(0, "Test");
		displayLCDCenteredString(1, "<   Select   >");
		
		if (nLCDButtons == left)
		{
			waitForRelease();
			page = 2;
		}
		
		else if (nLCDButtons == right)
		{
			waitForRelease();
			page = 0;
		}
		
		else if (nLCDButtons == center)
		{
			waitForRelease();
			Program = 4;
		}
	}
}
