#pragma config(Sensor, in1,    xAccel,         sensorAccelerometer)
#pragma config(Sensor, in2,    yAccel,         sensorAccelerometer)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*/////////////////// ++ Notes ++ /////////////////////

++ CONTROLS ++
Right Joystick Y                       Forward/Backward
Right Joystick C                       Left/Right
Left Joystick X                        Strafe Left/Right
All 3 LCD Buttons                      Back to LCD Main Menu

++PROGRMMING NOTES++
- Program 0 - LCD Main Menu
- Program 1 - User
- Program 2 - Auton
- Program 3 - Test

*//////////////////// ++ Notes ++ /////////////////////

/* Silly Auton Integer Setup */
int fMotorSpeed;
int bMotorSpeed;

/* LCD Integer Setup */
int page = 0;//Different Pages for the LCD
int Program = 0;//Runs the Main Code
int left = 1;//LCD Left Button
int center = 2;//LCD Center Button
int right = 4;//LCD Right Button
int xDisplay;
int yDisplay;

/* UserControl Integer Setup */
int Cha1 = 0;//Joystick Channel l Value
int Cha2 = 0;//Joystick Channel 2 Value
int Cha3 = 0;//Joystick Channel 3 Value
int Cha4 = 0;//Joystick Channel 4 Value
int RTthresh = 15;//Threshold for Joystick
int nRTthresh = RTthresh * 2; //Negative threshold for joystick

/* Autonomous Integer Setup */
int currentX;
int currentY;
int threshold = 3;
/*
int place;
int xPos;
int xNeg;
int yPos;
int yNeg;
*/

/* Includes */
#include "miscVoid.h";
#include "LCD.h";
#include "userControl.h";
#include "Auton.h";
#include "sillyAuton.h";

task main()
{
	///////
	// LCD CODE
	///////
	while (Program == 0)
	{
		LCD();
	}

	///////
	// USER CONTROL CODE
	///////
	while(Program == 1)
	{
		/* LCD Display */
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "- Running -");
		displayLCDCenteredString(1, "User Control");

		/* User Control File */
		userControl();
	}

	///////
	// AUTONOMOUS CODE
	///////
	while(Program == 2)
	{
		xDisplay = SensorValue(xAccel);
		yDisplay = SensorValue(yAccel);

		/* LCD Display */
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDNumber(0, 1, xDisplay);
		displayLCDNumber(1, 1, yDisplay);

		/* Auton  */
		Auton();
	}

	///////
	// SILLY AUTON CODE
	///////
	while (Program == 3)
	{
		/* LCD Display */
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "- Running -");
		displayLCDCenteredString(1, "Silly Auton");

		fMotorSpeed = 127;
		sillyAuton();
	}

	///////
	// TEST CODE
	///////
	while (Program == 4)
	{
		/* LCD Display */
		clearLCDLine(0);
		clearLCDLine(1);
		displayLCDCenteredString(0, "- Running -");
		displayLCDCenteredString(1, "Test");

		/* Test Code Goes Here */

		// Instead of making a new program to test
		// (eg. variables) for the robot, that code
		// would go here

	}
}
