#pragma config(Sensor, in1,    xAccel,         sensorAccelerometer)
#pragma config(Sensor, in2,    yAccel,         sensorAccelerometer)
#pragma config(Motor,  port2,           frontRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           backRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           frontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           backLeft,      tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Integer Setup */

/////
// User Control Void
/////
void userControl()
{

	/* Joystick Channel 1 */
	/* Right Y Axis */
	if (vexRT[Ch1] > RTthresh || vexRT[Ch1] < RTthresh - nRTthresh)
	{
		Cha1 = vexRT[Ch1];
	}
	else if (vexRT[Ch1] < RTthresh || vexRT[Ch1] > RTthresh - nRTthresh)
	{
		Cha1 = 0;
	}

	/* Joystick Channel 2 */
	/* Right X Axis */
	if (vexRT[Ch2] > RTthresh || vexRT[Ch2] < RTthresh - nRTthresh)
	{
		Cha2 = vexRT[Ch2];
	}
	else if (vexRT[Ch2] < RTthresh || vexRT[Ch2] > RTthresh - nRTthresh)
	{
		Cha2 = 0;
	}

	/* Joystick Channel 3 */
	/* Left X Axis */
	if (vexRT[Ch3] > RTthresh || vexRT[Ch3] < RTthresh - nRTthresh)
	{
		Cha3 = vexRT[Ch3];
	}
	else if (vexRT[Ch3] < RTthresh || vexRT[Ch3] > RTthresh - nRTthresh)
	{
		Cha3 = 0;
	}

	/* Joystick Channel 4 */
	/* Left Y Axis */
	if (vexRT[Ch4] > RTthresh || vexRT[Ch4] < RTthresh - nRTthresh)
	{
		Cha4 = vexRT[Ch4];
	}
	else if (vexRT[Ch4] < RTthresh || vexRT[Ch4] > RTthresh - nRTthresh)
	{ 
		Cha4 = 0;
	}

	/* Setting Motor Values */
	motor[frontRight] = Cha2 - Cha3 - Cha1;
	motor[backRight] = Cha2 - Cha3 + Cha1;
	motor[frontLeft] = Cha2 + Cha3 + Cha1;
	motor[backLeft] = Cha2 + Cha3 - Cha1;
}
